### ISSUE TITLE
CODE BREAKING BUG FOUND AT LINE: 9 of XMLDriver.java

### ISSUE THREAD

**Issue by chunkbin** [AlexDGr8r/Java-Programs-made-in-School#1]
Basically. You suck. @author "Alex Risner"

**Comment by AlexDGr8r** [comment]
Lol. Is this some sort of troll or something? There is nothing on those lines.

**Comment by chunkbin** [comment]
You should seriousally take this down though. A bunch of tech students are using it for their homework/labs. And if the university finds out it comes from your github they can revoke your degree for cheating.
